/*
 * Copyright 2021 Kristian Huang <kristianhuang@gmail.com>. All rights reserved.
 * Use of this source code is governed by a MIT style
 * license that can be found in the LICENSE file.
 */

// Package pump does all the work necessary to create an iam pump server.
package pump

import (
	genericapiserver "cooool-blog-api/internal/pkg/server"
	"cooool-blog-api/internal/pump/config"
	"cooool-blog-api/internal/pump/options"
	"cooool-blog-api/pkg/app"
	log "cooool-blog-api/pkg/rollinglog"
)

const commandDesc = `cooool-blog Pump is a pluggable analytics purger to move Analytics generated by your iam nodes to any back-end.
`

// NewApp creates an App object with default parameters.
func NewApp(use string) *app.App {
	opts := options.NewOptions()
	application := app.NewApp(
		use,
		"analytics-server",
		app.WithOptions(opts),
		app.WithLong(commandDesc),
		app.WithDefaultValidArgs(),
		app.WithRunFunc(run(opts)),
	)

	return application
}

func run(opts *options.Options) app.RunFunc {
	return func(basename string) error {
		log.Init(opts.Log)
		defer log.Flush()

		cfg, err := config.CreateConfigFromOptions(opts)
		if err != nil {
			return err
		}

		stopCh := genericapiserver.SetupSignalHandler()

		return Run(cfg, stopCh)
	}
}

// Run runs the specified pump server. This should never exit.
func Run(cfg *config.Config, stopCh <-chan struct{}) error {
	go genericapiserver.ServeHealthCheck(cfg.HealthCheckPath, cfg.HealthCheckAddress)

	// TODO on develop

	return nil
}
